/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "spring-testcontainers"
include("spring-testcontainers")
include("modules")
include("modules:postgresql")
include("modules:mysql")
include("modules:ollama")
include("examples")
include("examples:springboot-postgresql")
include("examples:spring-postgresql")
include("examples:springboot-mysql")
include("examples:springboot-ollama")
include("examples:springboot-kafka")
include("modules:kafka")
include("modules:jdbc")